[package]
name = "Balrs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1", features = ["full"]}
hyper = {version = "1.4", features = ["full"]}
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
whoami = "1.5.0"
reqwest = "0.12"
clap = { version = "4.5", features = ["cargo"] }