services:
  flask-app-3000:
    build: .
    ports:
      - "3000:3000"
    command: python app.py 3000

  flask-app-3001:
    build: .
    ports:
      - "3001:3001"
    command: python app.py 3001

  flask-app-3002:
    build: .
    ports:
      - "3002:3002"
    command: python app.py 3002

  flask-app-3003:
    build: .
    ports:
      - "3003:3003"
    command: python app.py 3003

  redis:
    image: "redis:alpine"
