[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/get_uris.rs"

[dependencies]
csv = "1.3.0"

hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }